name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t bilaalahmedr/gcp:latest .

    - name: Push to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      run: docker push bilaalahmedr/gcp:latest

  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Pull and run Docker image
      run: docker run -d bilaalahmedr/gcp:latest
